A <%= @exception.class %> occurred in <%= @controller.controller_name xxx@xxx.xxx %>:

  xxx@xxx.xxx %>
  xxx@xxx.xxx %>

xxx@xxx.xxx { |section| render_section(section) }.join %>
